### PR TITLE
Getting started with Configuration and Snapshot, SSHBackup, and LocalBackup classes

### PR DESCRIPTION
**Pull request by NicholasBHubbard**
I created this branch called `getting-setup`. I am thinking we can all work from this branch (and thus this PR) while we figure out some of the fundamental architecture of the project.

 I added a commit with some basic scaffolding. I implemented what I believe to be a working outline of a constructor for the `Config` class. To get this code to work we need to create `Snapshot`, `SSHBackup`, and `LocalBackup` classes. We also need to create a `__valid_setting()` function that ensures we only allow valid settings in our config. I hope the current implementation of this function communicates my vision for this class and how it will drive our design.

In the end we will be able to create our `Config` object with `config = Config.new("/path/to/config.yaml")`. For some more details on what these classes  may do see their yabsm equivalents here: [Yabsm::Snapshot](https://github.com/NicholasBHubbard/Yabsm/blob/master/lib/App/Yabsm/Snapshot.pm), [Yabsm::Backup::SSH](https://github.com/NicholasBHubbard/Yabsm/blob/master/lib/App/Yabsm/Backup/SSH.pm), [Yabsm::Backup::Local](https://github.com/NicholasBHubbard/Yabsm/blob/master/lib/App/Yabsm/Backup/Local.pm).

I *think* we can make some sort of abstract base class that our `Snapshot`, `SSHBackup`, and `LocalBackup` classes can all inherit from. All these classes should create objects that can be used to create a copy of some directory and place that directory somewhere. Are there other commonalities we can think of between these things? Do you guys think an abstract class for these to inherit from can benefit us in some way?

Let me know if you have any questions or anything is unclear :)

### CODE REVIEW

**Comment by NicholasBHubbard** [comment]
Thanks for the 016b25f commit @Vultimate1, nice work!

Could you explain your reasoning for adding separate directories for `full_backup_directory`, `incremental_backup_dir`, and `differential_backup_dir`?

Could you also explain why you added a `RemoteBackup` type? What is the difference between a `RemoteBackup` and an `SSHBackup`?

**Comment by NicholasBHubbard** [comment]
commit 187732f implements an abstract base class (using the Python [abc module)](https://docs.python.org/3/library/abc.html) for the Snapshot, LocalBackup, and RemoteBackup classes to inherit from. I abstracted out the things that all objects of these classes should do, such as creating a backup/snapshot, bootstrapping their environment, cleaning up after performing a backup/snapshot, etc. This is not a complete definition for everything these classes will need to do, and is meant to just be a foundational start. I am hoping this commit continues forward the process of fleshing out a general architectural structure for yaesm.

**Comment by NicholasBHubbard** [comment]
commit 3be94be get everything to a somewhat functional point (i.e. no syntax or import errors). Now our program (kind of) runs!

```
>>> from config import Config
>>> c = Config("/home/_73/p/scratch/yaesm-test-config.yaml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/_73/p/yaesm/src/yaesm/config.py", line 91, in __init__
    snapshot = Snapshot(name, vals)
TypeError: Can't instantiate abstract class Snapshot with abstract methods all_existing, bootstrap, cleanup, execute

```

**Comment by NicholasBHubbard** [comment]
I have created what I believe to be a nice and simple architectural setup for yaesm. I have done away with the whole concept of snapshots, remote_backups, and local_backups. Now all we have is the single concept of a "backup", and to use yaesm you just define a bunch of them in your configuration.

Please take a look at this example configuration file (which is much simpler than its predecessors):

```
---
# This is an example yaesm configuration file

root_backup:
  backend: rsync
  src_dir: /
  dst_dir: /mnt/backupdrive/yaesm/root_backup

  # This backup uses every timeframe category
  timeframes: [5minute, hourly, daily, weekly, monthly, yearly]

  5minute_keep: 24

  hourly_minutes: [0, 30]
  hourly_keep: 48

  daily_times: [23:59, 11:59]
  daily_keep: 720 # can go back an entire year!

  weekly_keep: 21
  weekly_days: [monday, friday, sunday]
  weekly_times: [23:59, 05:30]

  monthly_keep: 100
  monthly_days: [1, 7, 30]
  monthly_times: [23:59]

  yearly_keep: 5
  yearly_days: [1, 129]
  yearly_times: [23:59]

home_backup:
  backend: btrfs
  src_dir: /home/fred
  dst_dir: fred@192.168.1.73:/yaesm/fred_laptop_backups # backup to a remote server with SSH!
  ssh_key: /home/fred/.ssh/id_rsa
  timeframes: [daily]
  daily_times: [23:59]
  daily_keep: 365

database_snapshot:
  backend: zfs
  src_dir: /important-database
  dst_dir: /.snapshots/yaesm/important-database
  timeframes: [hourly]
  hourly_keep: 100000000000 # forever ... until we run out of disk space
  hourly_minutes: [0]
```

We no longer need an abstract base class for the different backup types, now we just have a single `Backup` class. The complexity of managing snapshots vs local/remote backups is now shifted into the backends. It is up to each backend to implement the abstract methods defined in the BackendBase base class.

Also note that each backup defines a `backend` which means we wont have to worry about autodetection at this point.

We are going to need to create some sort of t`Timeframe` class. Notice how certain timeframe settings are required if and only if that timeframe category is being used. For example, a backup that is not using the `yearly` timeframe category does not need to specify the settings `yearly_keep`, `yearly_days`, or `yearly_times`. It will be important to only accept valid timeframe settings, and to give good error messages for improper timeframe settings.

I would be comfortable merging this PR now. I think it gives us a good starting point.

**Comment by Vultimate1** [comment]
Sounds great!  Now the rsync only having a backup protocol and other distros having snapshot and backup capabilities can be handled separately.  Great work, I'll merge this.

**Pull request merged**
